/**
 * PS4 HEN Store - Game Catalog
 * Auto-generated by Admin Dashboard
 * Last updated: 2026-02-07T05:20:37.524Z
 * 
 * Cara menggunakan:
 * 1. Ganti file js/games-data.js di project Anda dengan file ini
 * 2. Refresh halaman store untuk melihat perubahan
 */

const PS4_GAME_CATALOG = [
    {
        id: 309,
        "createdAt": "2026-02-07T04:53:44.711Z",
        downloads: 0,
        title: "EA Sports FC 26 - Unlock",
        category: "dlc",
        publisher: "Electronic Arts",
        version: "1.0",
        rating: "E",
        size: 107374,
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/co0KgJdKPg7eqWw4nde-%5BPS4ID%5D-EA.SPORTS.FC.26_CUSA52342_Unlock-Offline_OPOISSO893.pkg?access=QahRDZ1tmayZWYwRWdwonMxZWc5oXdyJGdsJTb&token=PzEhXy0lM1khIFw4NC48IDdPNChKU1grJzQhKlFTXUBWPicFCA4NH0kuFA0ICAAROy4iJC0yPTtcWEFFFAoJ",
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhfaOmGIyJ-s5pLu5OsW0WNb7UfD5AztLpk3QY_rxvjgRyZcIKq4Ah2Z_-WPw0rwbo8gmKfiek5FnI8YGXtwAgiIzImTZ7C5UCdSCq1jwjFDHP4YOtGRuuLy0BS2VmS7pzbcZq97Y2mYjpPKilvLDD7z_7xBilsbs_ccMQXyPFr6W500NtP8Fy6Bbzes1U5/w400-h225/EA%20Sports%20FC%2026.jpg",
        description: "Unlock"
    },
    {
        id: 1,
        title: "PES 2026",
        category: "games",
        contentId: "EP9000-CUSA00207_00-PES202600000000",
        version: "1.0",
        size: 64949672960,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSnWPUdC9FSVy6WsmHaRTi1GFfPD9dtPg6rQ&s",
        description: "Bola sepak modern dengan grafis realistis dan gameplay mendalam. Nikmati pengalaman sepak bola tercanggih dengan visual stunning dan gameplay realistis.",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/coGs9s4EBR0mDTAWMde-BASE GAME BITBOX PATCH SUMMER 2026_2.pkg?access=QbhVDZ1tWbyBTYiRGawQHOylHNtFmbuVTesVXb&token=JiAhLkQmLzkhQTAiMCMhLEQxMz8nKU4nMSw_LjZBXERWVy1ZShEFEw",
        rating: "E",
        publisher: "Konami",
        downloads: 0,
        "createdAt": "2026-02-07T02:33:53.918Z",
        "updatedAt": "2026-02-07T03:29:57.481Z"
    },
    {
        id: 2,
        title: "GTA V - Grand Theft Auto V",
        category: "games",
        contentId: "EP1004-CUSA00419_00-GTA5000000000000",
        version: "1.0",
        size: 51539607552,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi7qkEUE4EX4FL_ArO5BrmUWRZHOyfW_nBuUJZr4MUvBGPw27swkk6mICitdXzG7EC5NEayg9ag_djWHOzOh4mcDx4jQVDimKxxhal9kwvrm0tEdqCEmgf9D2YCwEVnrRoeM6zzkUU7wgVs7JAXJRKjFWTHovL8rR2HvAhRmpscGRYzt94flSkIc-iZE1qv/w400-h224/g1.jpg",
        description: "Grand Theft Auto V adalah salah satu game aksi-petualangan terpopuler yang dirilis oleh Rockstar Games.Grand Theft Auto V adalah game aksi-petualangan yang menawarkan pengalaman dunia terbuka yang mendalam dan luas. Dalam game ini, Anda akan menjelajahi kota Los Santos yang kaya dengan berbagai aktivitas dan misi, serta mengikuti kisah tiga karakter yang saling terhubung dalam dunia kriminal.\n\nIkuti kisah tiga protagonis utama — Michael De Santa, Franklin Clinton, dan Trevor Philips — yang masing-masing memiliki latar belakang dan motivasi yang berbeda. Cerita ini terjalin dalam berbagai misi yang menarik dan penuh aksi.",
        url: "https://eeur1.akirabox.com/uploads/users/AY2xm0Ao3RO1/coWqnczUZKGdm9emJde-%5BPS4ID%5D-gtav.v1.00-00411.pkg?access=wahVHZntWayhWYtRGOwcXa5MGc1NWclJmbsdWb",
        rating: "M",
        publisher: "Rockstar Games",
        downloads: 0,
        "createdAt": "2026-02-06T23:47:13.918Z",
        "updatedAt": "2026-02-07T03:30:04.965Z"
    },
    {
        id: 3,
        title: "God of War Ragnarok",
        category: "games",
        contentId: "EP9000-CUSA07368_00-GODOFWAR0000000",
        version: "1.00",
        size: 90623809946,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi-ce5Kb_RyDM7i640rvze82ntIGugPHxtaxsxuZ0gh5Ws4NVd-DBmvzaUptEkD7UGQUXS1TqyLfXMTkZQppytk317NzjXmAOglkXKVeIX06qn9PkGYcjRYBo_4Hq6mCGfW3D6gXxkXmHZYRYe93Fsc25OxLR84zmD7_K7D_ptufef73GoiVpsmRxk0SZI-/w400-h221/g1.jpg",
        description: "God of War Ragnarok adalah sekuel dari game “God of War” (2018) yang dikembangkan oleh Santa Monica Studio dan dirilis oleh Sony Interactive Entertainment. Game ini melanjutkan kisah Kratos dan putranya, Atreus, dalam sebuah petualangan epik di dunia mitologi Nordik.\n\nCerita yang Mendalam Lanjutkan perjalanan Kratos dan Atreus saat mereka menghadapi ancaman dari para dewa Nordik dan kekuatan jahat yang ingin menghancurkan dunia.\nGameplay yang Ditingkatkan: Nikmati pertarungan yang intens dengan berbagai kemampuan dan senjata baru. Kombinasi serangan yang mematikan dan strategi tempur yang mendalam.\nDunia Terbuka: Eksplorasi dunia yang lebih luas dan detail, dengan berbagai lokasi yang dapat dijelajahi, termasuk wilayah baru dan musuh yang lebih kuat.\nGrafis dan Visual: Dapatkan pengalaman visual yang memukau dengan grafis yang lebih baik dan desain dunia yang kaya dan detail.",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/corDcjxIdddqM5Sy8de-%5BPS4ID%5D-God.of.War.Ragnarok_CUSA34386_v1.00_%5B9.00%5D_OPOISSO893.pkg?access=QZhhDZutWcy5WY0R2dwQzanFzN4Yjc0I2YsBXb&token=PzEhXy0lM1kjDhZFCwdAIwUTXDkFBgAVFg4ZNCc0PTVXVUFTUj4YRUpRQjQ_WEBEVDwtJDQuJyc3LkpSV08eHwM",
        rating: "M",
        publisher: "Sony Interactive Entertainment",
        downloads: 0,
        "createdAt": "2026-02-06T21:00:33.918Z",
        "updatedAt": "2026-02-07T03:29:48.595Z"
    },
    {
        id: 4,
        title: "Red Dead Redemption 2",
        category: "games",
        contentId: "EP1004-CUSA03041_00-RDR2S00000000000",
        version: "1.00",
        size: 107374182400,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhZzBej34Alv2pFsaVAlHppLkU6JgK9z6ZSx5nA8w_UROAbx2KdX5mJXSZtChJRoE7_5ArJ0GjSBPUVVHc7khU5xg0UNziE8xRYDp840TY8irVzzx26w4Uqc2hfA39dvoka1GPAq04DHcjJN0yChfKfzXPvuZ5gfzxHrZEeKD_cbhW4XNW5QMVi-_HspdCs/w400-h225/RDR2.jpg",
        description: "Red Dead Redemption 2 adalah game aksi-petualangan yang dirilis oleh Rockstar Games.Red Dead Redemption 2 adalah sebuah game aksi-petualangan yang menawarkan pengalaman dunia terbuka yang mendalam dan realistis, berlatar belakang Amerika Serikat akhir abad ke-19. Game ini merupakan prekuel dari Red Dead Redemption dan menempatkan pemain dalam peran Arthur Morgan, seorang anggota kelompok penjahat yang menghadapi berbagai tantangan dalam dunia yang sedang berubah.",
        url: "https://example.com/games/rdr2.pkg",
        rating: "M",
        publisher: "Rockstar Games",
        downloads: 0,
        "createdAt": "2026-02-06T18:13:53.918Z",
        "updatedAt": "2026-02-07T03:36:40.600Z"
    },
    {
        id: 5,
        title: "The Last of Us Part II",
        category: "games",
        contentId: "EP9000-CUSA07820_00-THELASTOFUSPART2",
        version: "1.00",
        size: 92943092285,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEim_D4wWYbM3FnJl5Lhwf9QqMqZXBe7LDJ5_F2nj86w6jXwMjirrH3fF6LLGt3WZ9cDZZoh00wIYNImGjSZjXFKCypTj5FUc_7Vbp9BRs3FPX56BaSqMQsqRtFduJfVR5pKuIeru9OOVgIlrRlTiRjkC3ceui5GahBh91oMSjNYqdAa_EM-wg4le0wDRLP6/w400-h225/The%20Last%20of%20Us%20Part%20II.jpg",
        description: "The Last of Us Part II adalah sekuel yang sangat dinantikan dari game pemenang penghargaan, The Last of Us, yang dikembangkan oleh Naughty Dog untuk PlayStation 4. Dalam game ini, kamu akan melanjutkan perjalanan emosional dan mendalam di dunia pasca-apokaliptik yang penuh dengan ketegangan dan konflik.\n\nIkuti kisah Ellie, yang kini menjadi protagonis utama, saat ia menghadapi tantangan baru dan perjalanan emosional yang berat. Cerita ini menggali tema tentang balas dendam, pengampunan, dan kompleksitas moral, menjadikannya sebuah pengalaman naratif yang mendalam dan penuh emosi.",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/coOZrp2bhnRFcnWsode-%5BPS4ID%5D-The.Last.of.Us.Part.2_CUSA10249_v1.00-PS4.pkg?access=AOhBHZ0t2byJWYkRmYvZDOhZHbs9mcpJGdsVWb&token=PzEhXy0lM1kwCRdFKAAdAEoOFEUxEkAkBRMGRVY-LSE3IENbVlVXKxJQXFtUTD4nUE8CAAM",
        rating: "M",
        publisher: "Sony Interactive Entertainment",
        downloads: 0,
        "createdAt": "2026-02-06T15:27:13.918Z",
        "updatedAt": "2026-02-07T03:39:26.583Z"
    },
    {
        id: 7,
        title: "Ghost of Tsushima",
        category: "games",
        contentId: "EP9000-CUSA17280_00-GHOSTTSUSHIMAMAIN",
        version: "2.24",
        size: 48651242045,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg3h7JJSjS55AoXYnTAnG6BfATMPBa-p5q5yjGi42YRQsUJ2DTguJtlp1wPpIlKN_VTEmAX7uzd9j2453-QDZurglCSlevhfEecrbqKHHs2aze9WAKcnlJnKdCxGyGZIgLZ-Mkz5fbA6vMjb266_qs8d4VfvqmTuZQh9dPxD5MpLD201H3FvCj6944e6Mjg/w400-h229/G1.jpg",
        description: "Ghost of Tsushima Director’s Cut adalah versi perluasan dari permainan aksi petualangan yang sangat dihargai, dirilis untuk PlayStation 4 dan PlayStation 5. Dikembangkan oleh Sucker Punch Productions dan dipublikasikan oleh Sony Interactive Entertainment, permainan ini menempatkan1 Player pemain dalam peran Jin Sakai, seorang samurai yang bertempur untuk melindungi pulau Tsushima dari invasi Mongol pada abad ke-13.",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/coY6liDDlmWHu9Lecde-%5BPS4ID%60%5D-Ghost.of.Tsushima_CUSA13323_FULLGAME_v2.24_%5B9.00-11.00%5D-PS4.pkg?access=QOhhDZws2cyJWYrR2dwI3bsl3c25mc2JWYsJTb&token=PzEhXy0lDilJJhoEFxVAGwJPJhgREgYdCQAtKDEyL0VXUkBYOyc7OCgmMyYhPhhGSlNGND9YQERUTENaSlFeKUkxIV9KEQUT",
        rating: "M",
        publisher: "Sucker Punch Productions",
        downloads: 0,
        "createdAt": "2026-02-06T09:53:53.918Z",
        "updatedAt": "2026-02-07T03:47:47.299Z"
    },
    {
        id: 9,
        title: "Minecraft PS4 Edition",
        category: "games",
        contentId: "EP1004-CUSA00744_00-MINECRAFTPS40001",
        version: "1.00",
        size: 107374182,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh_QYayD0v4CM_30PrN1iUZEZd5iCB9WXbkb5q4NFHvVgnxEUoAi6-c_KYjVnBXfs_Fhz9PeH87s8kWU5hOM6p0BYG-P-ndM_IC0zXtB57_hi7PZ7qDEH2DPU9En0IIeeT2x4Mb-6bgNkBNB_ZQH68ak3lQTqyFJ75LS1TAzf4yM1eNQcypShuLC-cB728x/w400-h215/Minecraft%20PlayStation%204%20Edition.jpg",
        description: "Game sandbox legendaris. Bangun, tambang, dan bertahan hidup di dunia blok!",
        url: "https://eeur1.akirabox.com/uploads/users/AY2xm0Ao3RO1/coNj1B2ssNUoil3Lade-%5BPS4ID%5D-minecraft.v1.00-00265.pkg?access=QOhxGZktGayZTY0QGawI2bytmN4kDd2J2ZsZTb",
        rating: "E10+",
        publisher: "Mojang Studios",
        downloads: 0,
        "createdAt": "2026-02-06T04:20:33.918Z",
        "updatedAt": "2026-02-07T04:46:27.929Z"
    },
    {
        id: 10,
        title: "EA Sports FC 26",
        category: "games",
        contentId: "EP0001-CUSA32278_00-FIFAFC24DELDX000",
        version: "1.0",
        size: 15945066086,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhfaOmGIyJ-s5pLu5OsW0WNb7UfD5AztLpk3QY_rxvjgRyZcIKq4Ah2Z_-WPw0rwbo8gmKfiek5FnI8YGXtwAgiIzImTZ7C5UCdSCq1jwjFDHP4YOtGRuuLy0BS2VmS7pzbcZq97Y2mYjpPKilvLDD7z_7xBilsbs_ccMQXyPFr6W500NtP8Fy6Bbzes1U5/w400-h225/EA%20Sports%20FC%2026.jpg",
        description: "EA Sports FC 26 untuk PS4 menghadirkan pengalaman sepak bola yang lebih tajam berkat sejumlah penyempurnaan gameplay berdasarkan masukan komunitas. Kamu akan merasakan dribel yang lebih responsif, posisi AI pemain yang lebih pintar, dan reaksi kiper yang lebih alami sehingga pertandingan terasa lebih realistis.",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/cooXBSDu64iF4rxt6de-%5BPS4ID%5D-EA.SPORTS.FC.26_CUSA52342_v1.00_%5B12.50%5D_OPOISSO893.pkg?access=AOhxGZ3sWaydTY2R2d4kWe4wWczIXd0JGdshXb&token=PzEhXy0lM1khIFw4NC48IDdPNChKU1grJzQhKlFTXUBWPgRaSlFeKz9QQEVRUTMrKzE9IjcyIUxdUlwbDwY",
        rating: "E",
        publisher: "Electronic Arts",
        downloads: 0,
        "createdAt": "2026-02-06T01:33:53.918Z",
        "updatedAt": "2026-02-07T04:50:26.056Z"
    },
    {
        id: 11,
        title: "Mortal Kombat 11",
        category: "games",
        contentId: "EP1018-CUSA14335_00-MORTALKOMBAT1111",
        version: "1.00",
        size: 39889508762,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjBOBOEuzXiygdDG33DAZ14ll9D1WHVbfUg4c2uLgCmTmuq_kBIWZVYepZMrvR3kkGO0risIOaNwlJCJTPGMTkk_llKGY3b-6WC0PZQ3Q3XqfZYduMu7ozscff5jsdOqkMhPEgw3Z3XJaJS8rXtK2b06vTRjA69UqoEMebeIYWECRlualf7EtU8nbWUO83q/w400-h220/k1.jpg",
        description: "Mortal Kombat 11 Ultimate Edition adalah edisi khusus dari game pertarungan legendaris yang dirilis untuk PlayStation 4.\n\nMortal Kombat 11 Ultimate Edition adalah versi lengkap dan terbaru dari game pertarungan terkenal Mortal Kombat 11. Edisi ini mencakup semua konten tambahan dan ekspansi yang dirilis untuk game ini, menawarkan pengalaman bertarung yang lebih komprehensif dan mendalam.",
        url: "https://eeur1.akirabox.com/uploads/users/AY2xm0Ao3RO1/cozdGfz4p4EApEZesde-%5BPS4ID%5D-Mortal.Kombat.11.Ultimate-CUSA11379-EUR-Game-v1.00_%5B6.72%5D_OPOISSO893.pkg?access=wMhlGZ5tGeyZTYjRWYwEWe2kzbkBXdzIWYshWb",
        rating: "M",
        publisher: "Warner Bros",
        downloads: 0,
        "createdAt": "2026-02-05T22:47:13.918Z",
        "updatedAt": "2026-02-07T04:56:36.009Z"
    },
    {
        id: 12,
        title: "Resident Evil 2 Remake",
        category: "games",
        contentId: "EP0102-CUSA14183_00-BH2REMASTER00000",
        version: "1.00",
        size: 23203560817,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgqUOp8J8cPRRd_77Cx_mXocMDdjhYb1MlpvMxvpUjns5-rVc7PN3RPY1YFvYs_jimvT-bP_GRIM54B9RoFJwe8fLF2c0qgXqjqvYAq9U7qxVP_6lvVaJZcrRAc-eppsrOUX5nobKA_LNAEdqG2BMIuMmYU8o2BPOHt4I3qSx7_DhoyLRTdXhKYj4d5MsI8/w400-h225/Resident%20Evil%202%20Remake%20Deluxe%20Edition.png",
        description: "Resident Evil 2 Remake Deluxe Edition membawa kembali pengalaman menegangkan dari game survival horror ikonik dengan grafis modern dan mekanisme gameplay yang diperbarui. Versi Deluxe Edition menawarkan lebih dari sekadar remaster; ini adalah pembaharuan yang menyegarkan dengan tambahan konten eksklusif yang memperkaya pengalaman bermain.",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/coN80EtQfUQQKzsuYde-%5BPS4ID%5D-Resident.Evil.2.v1.00-CUSA09171.pkg?access=gahZHZ0tWOyJTY3QmZjl2N0V3dxEmdyJGOsNWb&token=PzEhXy0lM1k2BAECAAQAAEokBAIIT1xaElBcW1RMLSE3IEJSVVZfWhQKFQ",
        rating: "M",
        publisher: "Capcom",
        downloads: 0,
        "createdAt": "2026-02-05T20:00:33.918Z",
        "updatedAt": "2026-02-07T05:15:44.966Z"
    },
    {
        id: 13,
        title: "Cyberpunk 2077",
        category: "games",
        contentId: "EP4497-CUSA16512_00-CYBERPUNK2077000",
        version: "2.1",
        size: 70877697802,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhtaec_nvWuhsCBFZvycYReqdX-Lvs440W55iXZJU7asv4wbVycCGcWMeRdIhgPksjNondjBTFgpIWdDGGFyAFfPE-7U2OKsxOAu6U7icwB4cUf-2cVLggsZkUYeBw_N1DafHXOBslN9oJJJ59j6aG8i9OBTX3FJhBnprnnkAhSUCX29M7OPb6Ph5ZHIVZ3/w400-h225/Cyberpunk%202077.jpg",
        description: "RPG open-world di masa depan dystopia. Jadilah cyberpunk legendaris!",
        url: "https://eeur1.akirabox.com/uploads/users/AY2xm0Ao3RO1/co6jDfaGfGnq67bWede-%5BPS4ID%5D.cyb2k77.v1.61.merged-16579.pkg?access=gNhBDZptGOylTY0QWMjtGanRHN3YmdyJWbsdTb",
        rating: "M",
        publisher: "CD Projekt Red",
        downloads: 0,
        "createdAt": "2026-02-05T17:13:53.918Z",
        "updatedAt": "2026-02-07T05:20:37.518Z"
    },
    {
        id: 14,
        title: "Call of Duty: Modern Warfare II",
        category: "games",
        contentId: "EP0002-CUSA16978_00-MWII202300000000",
        version: "1.2",
        size: 107374182400,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/MW2_COVER.png",
        description: "First-person shooter dengan campaign dan multiplayer epik.",
        url: "https://example.com/games/cod-mw2.pkg",
        rating: "M",
        publisher: "Activision",
        downloads: 19870,
        "createdAt": "2026-02-05T14:27:13.918Z"
    },
    {
        id: 15,
        title: "Need for Speed Heat",
        category: "games",
        contentId: "EP0006-CUSA15068_00-NFSHEAT000000001",
        version: "1.4",
        size: 42949672960,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/NFS_HEAT_COVER.png",
        description: "Game balapan ilegal di kota Palm City. Kustomisasi mobil dan gas penuh!",
        url: "https://example.com/games/nfs-heat.pkg",
        rating: "T",
        publisher: "Electronic Arts",
        downloads: 6540,
        "createdAt": "2026-02-05T11:40:33.918Z"
    },
    {
        id: 16,
        title: "DOOM Eternal",
        category: "games",
        contentId: "EP1003-CUSA08837_00-DOOMETERNALBDIG",
        version: "1.2",
        size: 42949672960,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/DOOM_ETERNAL.png",
        description: "Bantai pasukan neraka sebagai DOOM Slayer dalam aksi shooter intens!",
        url: "https://example.com/games/doom-eternal.pkg",
        rating: "M",
        publisher: "Bethesda",
        downloads: 9230,
        "createdAt": "2026-02-05T08:53:53.918Z"
    },
    {
        id: 17,
        title: "Assassin's Creed Valhalla",
        category: "games",
        contentId: "EP0001-CUSA18527_00-ASSASSINSVALHAL1",
        version: "1.5",
        size: 60129542144,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/AC_VALHALLA.png",
        description: "Petualangan Viking di era Invasi. Bangun klan dan taklukkan Inggris!",
        url: "https://example.com/games/ac-valhalla.pkg",
        rating: "M",
        publisher: "Ubisoft",
        downloads: 11890,
        "createdAt": "2026-02-05T06:07:13.918Z"
    },
    {
        id: 18,
        title: "Watch Dogs: Legion",
        category: "games",
        contentId: "EP0001-CUSA15241_00-WDLEGION0000000",
        version: "1.2",
        size: 51539607552,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/WD_LEGION.png",
        description: "Bangun perlawanan di London futuristic. Retas, infiltrasi, dan sabotase!",
        url: "https://example.com/games/watch-dogs-legion.pkg",
        rating: "M",
        publisher: "Ubisoft",
        downloads: 7850,
        "createdAt": "2026-02-05T03:20:33.918Z"
    },
    {
        id: 19,
        title: "Marvel's Avengers",
        category: "games",
        contentId: "EP0002-CUSA13127_00-AVENGERSCUSA1312",
        version: "3.8",
        size: 51539607552,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/AVENGERS_COVER.png",
        description: "Game superhero dengan Avengers. Mainkan Thor, Iron Man, dan lainnya!",
        url: "https://example.com/games/marvels-avengers.pkg",
        rating: "T",
        publisher: "Crystal Dynamics",
        downloads: 9120,
        "createdAt": "2026-02-05T00:33:53.918Z"
    },
    {
        id: 20,
        title: "Horizon Forbidden West",
        category: "games",
        contentId: "EP9000-CUSA247864_00-HORIZONFW0000000",
        version: "1.08",
        size: 68719476736,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/HORIZON_FW.png",
        description: "Aloy kembali dalam petualangan epik di dunia post-apocalyptic yang luas!",
        url: "https://example.com/games/horizon-fw.pkg",
        rating: "T",
        publisher: "Guerrilla Games",
        downloads: 16540,
        "createdAt": "2026-02-04T21:47:13.918Z"
    },
    {
        id: 101,
        title: "GoldHEN Cheat Repository",
        category: "apps",
        contentId: "HOMEBREW-CHEATS-001",
        version: "2.0",
        size: 10485760,
        image: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>💉</text></svg>",
        description: "Koleksi cheat dan mod untuk berbagai game PS4.",
        url: "https://example.com/homebrew/cheats.pkg",
        rating: "T",
        publisher: "Homebrew Community",
        downloads: 28930,
        "createdAt": "2026-02-04T19:00:33.918Z"
    },
    {
        id: 102,
        title: "PS4 Remote PKG Installer",
        category: "apps",
        contentId: "HOMEBREW-RPI-001",
        version: "3.0",
        size: 5242880,
        image: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>📦</text></svg>",
        description: "Install file PKG dari browser PC langsung ke PS4.",
        url: "https://example.com/homebrew/remote-pkg.pkg",
        rating: "T",
        publisher: "Homebrew Community",
        downloads: 45210,
        "createdAt": "2026-02-04T16:13:53.918Z"
    },
    {
        id: 103,
        title: "PS4 Game Dumper",
        category: "apps",
        contentId: "HOMEBREW-DUMPER-001",
        version: "1.5",
        size: 15728640,
        image: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>💾</text></svg>",
        description: "Backup game dan aplikasi dari PS4 ke USB.",
        url: "https://example.com/homebrew/game-dumper.pkg",
        rating: "T",
        publisher: "Homebrew Community",
        downloads: 23450,
        "createdAt": "2026-02-04T13:27:13.918Z"
    },
    {
        id: 104,
        title: "PS4 Theme Customizer",
        category: "apps",
        contentId: "HOMEBREW-THEME-001",
        version: "2.1",
        size: 20971520,
        image: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🎨</text></svg>",
        description: "Buat dan install tema kustom untuk PS4.",
        url: "https://example.com/homebrew/theme-customizer.pkg",
        rating: "T",
        publisher: "Homebrew Community",
        downloads: 18760,
        "createdAt": "2026-02-04T10:40:33.918Z"
    },
    {
        id: 105,
        title: "PS4 Save Mounter",
        category: "apps",
        contentId: "HOMEBREW-SAVE-001",
        version: "1.8",
        size: 8388608,
        image: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>💾</text></svg>",
        description: "Mount dan edit save game PS4 dengan mudah.",
        url: "https://example.com/homebrew/save-mounter.pkg",
        rating: "T",
        publisher: "Homebrew Community",
        downloads: 15670,
        "createdAt": "2026-02-04T07:53:53.918Z"
    },
    {
        id: 106,
        title: "FileZilla PS4",
        category: "apps",
        contentId: "HOMEBREW-FTP-001",
        version: "3.2",
        size: 12582912,
        image: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>📁</text></svg>",
        description: "FTP client untuk transfer file dari/ke PS4.",
        url: "https://example.com/homebrew/filezilla.pkg",
        rating: "T",
        publisher: "Homebrew Community",
        downloads: 21340,
        "createdAt": "2026-02-04T05:07:13.918Z"
    },
    {
        id: 107,
        title: "PS4 Toolbox",
        category: "apps",
        contentId: "HOMEBREW-TOOLBOX-001",
        version: "4.0",
        size: 31457280,
        image: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🔧</text></svg>",
        description: "Tools lengkap untuk PS4 homebrew - monitor, ftp, dan lainnya.",
        url: "https://example.com/homebrew/ps4-toolbox.pkg",
        rating: "T",
        publisher: "Homebrew Community",
        downloads: 34210,
        "createdAt": "2026-02-04T02:20:33.918Z"
    },
    {
        id: 108,
        title: "AppToHome",
        category: "apps",
        contentId: "HOMEBREW-ATH-001",
        version: "1.9",
        size: 6291456,
        image: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🏠</text></svg>",
        description: "Buat shortcut untuk aplikasi homebrew di homescreen PS4.",
        url: "https://example.com/homebrew/apptohome.pkg",
        rating: "T",
        publisher: "Homebrew Community",
        downloads: 28930,
        "createdAt": "2026-02-03T23:33:53.918Z"
    },
    {
        id: 201,
        title: "PES 2026 - REV 2 Update",
        category: "updates",
        contentId: "EP9000-CUSA00207_00-PES2026UPDATE002",
        version: "2.0",
        size: 4448720998,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSnWPUdC9FSVy6WsmHaRTi1GFfPD9dtPg6rQ&s",
        description: "Patch dan update terbaru untuk PES 2026. Fix bug dan peningkatan performa.",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/co9JVM7BGy6lBA3ROde-REV2%20PES%2026%20BITBOX%20PATCH.pkg?access=QehVDZ3tGNyFXYjRGezFTMyJmMqZmbvVDcsFTb&token=NiQkWUQxKydEU0RLJig6Nis5UjslNS08ShEZDA",
        rating: "E",
        publisher: "Konami",
        downloads: 0,
        "createdAt": "2026-02-03T20:47:13.918Z",
        "updatedAt": "2026-02-07T03:31:40.617Z"
    },
    {
        id: 202,
        title: "God of War - Update",
        category: "updates",
        contentId: "EP9000-CUSA07368_00-B00000000000000",
        version: "6.05",
        size: 25308094792,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi-ce5Kb_RyDM7i640rvze82ntIGugPHxtaxsxuZ0gh5Ws4NVd-DBmvzaUptEkD7UGQUXS1TqyLfXMTkZQppytk317NzjXmAOglkXKVeIX06qn9PkGYcjRYBo_4Hq6mCGfW3D6gXxkXmHZYRYe93Fsc25OxLR84zmD7_K7D_ptufef73GoiVpsmRxk0SZI-/w400-h221/g1.jpg",
        description: "Update 6.05 menambahkan New Game+ dan Photo Mode!",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/coc6JogHtLCS8k5TOde-%5BPS4ID%5D-God.of.War.Ragnarok_CUSA34386_v6.05_%5B9.00%5D-PS4.pkg?access=gahZDZntGeyFXYhRWZjZ2MwF2ZllncoJ2ZsVWb&token=PzEhXy0lM1kjDhZFCwdAIwUTXDkFBgAVFg4ZNCc0PTVXVUFTUj4YQkpRRzQ_WEBEVDxfOzdVQAQPBg",
        rating: "M",
        publisher: "Sony Interactive Entertainment",
        downloads: 0,
        "createdAt": "2026-02-03T18:00:33.918Z",
        "updatedAt": "2026-02-07T03:34:07.448Z"
    },
    {
        id: 203,
        title: "Spider-Man - Update 1.19",
        category: "updates",
        contentId: "EP9000-CUSA02299_00-SPIDERMANUPDATE",
        version: "1.19",
        size: 3221225472,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/6L7L8L8L8L8L8L8L8L8.png",
        description: "Update terbaru Spider-Man dengan perbaikan bug.",
        url: "https://example.com/updates/spiderman-update.pkg",
        rating: "T",
        publisher: "Insomniac Games",
        downloads: 7650,
        "createdAt": "2026-02-03T15:13:53.918Z"
    },
    {
        id: 205,
        title: "Minecraft PS4 - Update 2.35",
        category: "updates",
        contentId: "EP1004-CUSA00744_00-MCPS4UPDATE23500",
        version: "2.35",
        size: 1073741824,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/MC4PS4_LOGO_1200x668.png",
        description: "Update terbaru Minecraft dengan fitur baru dan bug fixes.",
        url: "https://example.com/updates/minecraft-update.pkg",
        rating: "E10+",
        publisher: "Mojang Studios",
        downloads: 14560,
        "createdAt": "2026-02-03T09:40:33.918Z"
    },
    {
        id: 301,
        title: "Bloodborne - The Old Hunters DLC",
        category: "dlc",
        contentId: "EP9000-CUSA00207_00-BLOODBORNEEXPAN1",
        version: "1.08",
        size: 10737418240,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/9K4EK2JH4KfG4JTuzKXiZ9z0.png",
        description: "Expand your hunt dengan senjata baru dan area baru di Old Hunters.",
        url: "https://example.com/dlc/bb-old-hunters.pkg",
        rating: "M",
        publisher: "FromSoftware",
        downloads: 6780,
        "createdAt": "2026-02-03T06:53:53.918Z"
    },
    {
        id: 302,
        title: "God of War - Digital Deluxe DLC",
        category: "dlc",
        contentId: "EP9000-CUSA07368_00-GOWDELUXEEDITION",
        version: "1.0",
        size: 2147483648,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/8f8dVZnJZnJJD6KZd5G8b0Z8.png",
        description: "Bonus Digital Deluxe: Armour set, EXP boosters, dan digital artbook.",
        url: "https://example.com/dlc/gow-deluxe.pkg",
        rating: "M",
        publisher: "Sony Interactive Entertainment",
        downloads: 4320,
        "createdAt": "2026-02-03T04:07:13.918Z"
    },
    {
        id: 303,
        title: "GTA V - Heists DLC",
        category: "dlc",
        contentId: "EP1004-CUSA00419_00-GTAHEISTSDLC000",
        version: "1.0",
        size: 3221225472,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/9P9Q9Q9Q9Q9Q9Q9Q9Q.png",
        description: "Bonus Heists content dengan kendaraan dan senjata eksklusif.",
        url: "https://example.com/dlc/gta-heists.pkg",
        rating: "M",
        publisher: "Rockstar Games",
        downloads: 5670,
        "createdAt": "2026-02-03T01:20:33.918Z"
    },
    {
        id: 304,
        title: "Spider-Man - City Never Sleeps DLC",
        category: "dlc",
        contentId: "EP9000-CUSA02299_00-SPIDERMANDLC0001",
        version: "1.1",
        size: 4294967296,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/6L7L8L8L8L8L8L8L8L8.png",
        description: "3 cerita DLC tambahan: Turf Wars, Silver Lining, dan The City That Never Sleeps.",
        url: "https://example.com/dlc/spiderman-dlc.pkg",
        rating: "T",
        publisher: "Insomniac Games",
        downloads: 7890,
        "createdAt": "2026-02-02T22:33:53.918Z"
    },
    {
        id: 305,
        title: "Mortal Kombat 11 - Kombat Pack 1",
        category: "dlc",
        contentId: "EP1018-CUSA14335_00-MK11KOMBATPAK01",
        version: "1.0",
        size: 6448720992,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/MK11_COVER.png",
        description: "5 karakter baru: Shang Tsung, Nightwolf, Sindel, General Shao, dan guest character.",
        url: "https://example.com/dlc/mk11-kp1.pkg",
        rating: "M",
        publisher: "Warner Bros",
        downloads: 5430,
        "createdAt": "2026-02-02T19:47:13.918Z"
    },
    {
        id: 306,
        title: "Assassin's Creed Valhalla - Season Pass",
        category: "dlc",
        contentId: "EP0001-CUSA18527_00-ACVSEASONPASS01",
        version: "1.0",
        size: 17179869184,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/AC_VALHALLA.png",
        description: "Season Pass dengan 2 ekspansi besar: The Siege of Paris dan The Rise of the Raid.",
        url: "https://example.com/dlc/acv-season-pass.pkg",
        rating: "M",
        publisher: "Ubisoft",
        downloads: 6540,
        "createdAt": "2026-02-02T17:00:33.918Z"
    },
    {
        id: 6,
        title: "Spider-Man",
        category: "games",
        contentId: "EP9000-CUSA02299_00-SPIDERMANFULLGAME",
        version: "1.19",
        size: 42949672960,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/6L7L8L8L8L8L8L8L8L8.png",
        description: "Terbang melintasi New York City sebagai Spider-Man dalam petualangan open-world yang spektakuler!",
        url: "https://example.com/games/spiderman.pkg",
        rating: "T",
        publisher: "Insomniac Games",
        downloads: 21560,
        "createdAt": "2026-02-07T03:52:10.819Z"
    },
    {
        id: 204,
        title: "Ghost of Tsushima - Update 2.18",
        category: "updates",
        contentId: "EP9000-CUSA17280_00-GHOSTUPDATE21800",
        version: "2.18",
        size: 5368709120,
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202311/1617/5K9K8K8K8K8K8K8K8K.png",
        description: "Update 2.18 dengan Legends mode improvements.",
        url: "https://example.com/updates/got-update.pkg",
        rating: "M",
        publisher: "Sucker Punch Productions",
        downloads: 5890,
        "createdAt": "2026-02-07T01:05:30.819Z"
    },
    {
        id: 307,
        "createdAt": "2026-02-07T04:02:04.486Z",
        downloads: 0,
        title: "The Last of Us Part II - Update",
        category: "updates",
        publisher: "Sony Interactive Entertainment",
        version: "1.09",
        rating: "E",
        size: 48962627174,
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/codg2Z2AHeBbC21jbde-hako.tloupii.v1.09.Update-10249.rar?access=QZhlGZ3tGNyRTYtRWcwcjMpVTeyJjcyJGesBXb&token=DAAZBEoVAhsRERsCShdfWlRYXD4UBQ8AAUxDW1ZVV1oWAAA",
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEim_D4wWYbM3FnJl5Lhwf9QqMqZXBe7LDJ5_F2nj86w6jXwMjirrH3fF6LLGt3WZ9cDZZoh00wIYNImGjSZjXFKCypTj5FUc_7Vbp9BRs3FPX56BaSqMQsqRtFduJfVR5pKuIeru9OOVgIlrRlTiRjkC3ceui5GahBh91oMSjNYqdAa_EM-wg4le0wDRLP6/w400-h225/The%20Last%20of%20Us%20Part%20II.jpg",
        description: ""
    },
    {
        id: 308,
        "createdAt": "2026-02-07T01:15:24.486Z",
        downloads: 0,
        title: "GTA V - Grand Theft Auto V",
        category: "updates",
        publisher: "Rockstar Games",
        version: "1.52",
        rating: "E",
        size: 48500918190,
        url: "https://eeur1.akirabox.com/uploads/users/AY2xm0Ao3RO1/cogObqdAKGZIoIXt8de-%5BPS4ID%5D-Grand.Theft.Auto.V.Update.v1.52-CUSA00411.pkg?access=AZhtGZ0t2NyVXYxRWZ3J3Y2VmcxkncyJWMshTb",
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi7qkEUE4EX4FL_ArO5BrmUWRZHOyfW_nBuUJZr4MUvBGPw27swkk6mICitdXzG7EC5NEayg9ag_djWHOzOh4mcDx4jQVDimKxxhal9kwvrm0tEdqCEmgf9D2YCwEVnrRoeM6zzkUU7wgVs7JAXJRKjFWTHovL8rR2HvAhRmpscGRYzt94flSkIc-iZE1qv/w400-h224/g1.jpg",
        description: "Grand Theft Auto V adalah salah satu game aksi-petualangan terpopuler yang dirilis oleh Rockstar Games.Grand Theft Auto V adalah game aksi-petualangan yang menawarkan pengalaman dunia terbuka yang mendalam dan luas. Dalam game ini, Anda akan menjelajahi kota Los Santos yang kaya dengan berbagai aktivitas dan misi, serta mengikuti kisah tiga karakter yang saling terhubung dalam dunia kriminal.\n\nIkuti kisah tiga protagonis utama — Michael De Santa, Franklin Clinton, dan Trevor Philips — yang masing-masing memiliki latar belakang dan motivasi yang berbeda. Cerita ini terjalin dalam berbagai misi yang menarik dan penuh aksi."
    }
];

// ========== HELPER FUNCTIONS ==========

function getAllGames() {
    return PS4_GAME_CATALOG;
}

function getGamesByCategory(category) {
    if (category === 'all') return PS4_GAME_CATALOG;
    return PS4_GAME_CATALOG.filter(game => game.category === category);
}

function getGameById(id) {
    return PS4_GAME_CATALOG.find(game => game.id === id);
}

function searchGames(query) {
    const lowerQuery = query.toLowerCase();
    return PS4_GAME_CATALOG.filter(game => 
        game.title.toLowerCase().includes(lowerQuery) ||
        (game.description && game.description.toLowerCase().includes(lowerQuery))
    );
}

function getFeaturedGames(limit = 4) {
    return PS4_GAME_CATALOG
        .filter(game => game.url && !game.url.includes('example.com'))
        .slice(0, limit);
}

function getTopDownloads(limit = 5) {
    return [...PS4_GAME_CATALOG]
        .sort((a, b) => (b.downloads || 0) - (a.downloads || 0))
        .slice(0, limit);
}

function getGameStats() {
    const games = PS4_GAME_CATALOG.filter(g => g.category === 'games');
    const apps = PS4_GAME_CATALOG.filter(g => g.category === 'apps');
    const updates = PS4_GAME_CATALOG.filter(g => g.category === 'updates');
    const dlc = PS4_GAME_CATALOG.filter(g => g.category === 'dlc');
    
    const totalSize = PS4_GAME_CATALOG.reduce((acc, g) => acc + (g.size || 0), 0);
    
    return {
        totalGames: games.length,
        totalApps: apps.length,
        totalUpdates: updates.length,
        totalDLC: dlc.length,
        totalItems: PS4_GAME_CATALOG.length,
        totalSize: totalSize
    };
}

function formatSize(bytes) {
    if (bytes === 0) return '0 B';
    const k = 1024;
    const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
}