/**
 * PS4 HEN Store - Game Catalog
 * Auto-generated by Admin Dashboard
 * Last updated: 2026-02-07T05:20:37.524Z
 * 
 * Cara menggunakan:
 * 1. Ganti file js/games-data.js di project Anda dengan file ini
 * 2. Refresh halaman store untuk melihat perubahan
 */

const PS4_GAME_CATALOG = [
    {
        id: 309,
        "createdAt": "2026-02-07T04:53:44.711Z",
        downloads: 0,
        title: "EA Sports FC 26 - Unlock",
        category: "dlc",
        publisher: "Electronic Arts",
        version: "1.0",
        rating: "E",
        size: 107374,
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/co0KgJdKPg7eqWw4nde-%5BPS4ID%5D-EA.SPORTS.FC.26_CUSA52342_Unlock-Offline_OPOISSO893.pkg?access=QahRDZ1tmayZWYwRWdwonMxZWc5oXdyJGdsJTb&token=PzEhXy0lM1khIFw4NC48IDdPNChKU1grJzQhKlFTXUBWPicFCA4NH0kuFA0ICAAROy4iJC0yPTtcWEFFFAoJ",
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhfaOmGIyJ-s5pLu5OsW0WNb7UfD5AztLpk3QY_rxvjgRyZcIKq4Ah2Z_-WPw0rwbo8gmKfiek5FnI8YGXtwAgiIzImTZ7C5UCdSCq1jwjFDHP4YOtGRuuLy0BS2VmS7pzbcZq97Y2mYjpPKilvLDD7z_7xBilsbs_ccMQXyPFr6W500NtP8Fy6Bbzes1U5/w400-h225/EA%20Sports%20FC%2026.jpg",
        description: "Unlock"
    },
    {
        id: 1,
        title: "PES 2026",
        category: "games",
        contentId: "EP9000-CUSA00207_00-PES202600000000",
        version: "1.0",
        size: 64949672960,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSnWPUdC9FSVy6WsmHaRTi1GFfPD9dtPg6rQ&s",
        description: "Bola sepak modern dengan grafis realistis dan gameplay mendalam. Nikmati pengalaman sepak bola tercanggih dengan visual stunning dan gameplay realistis.",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/coGs9s4EBR0mDTAWMde-BASE GAME BITBOX PATCH SUMMER 2026_2.pkg?access=QbhVDZ1tWbyBTYiRGawQHOylHNtFmbuVTesVXb&token=JiAhLkQmLzkhQTAiMCMhLEQxMz8nKU4nMSw_LjZBXERWVy1ZShEFEw",
        rating: "E",
        publisher: "Konami",
        downloads: 0,
        "createdAt": "2026-02-07T02:33:53.918Z",
        "updatedAt": "2026-02-07T03:29:57.481Z"
    },
    {
        id: 2,
        title: "GTA V - Grand Theft Auto V",
        category: "games",
        contentId: "EP1004-CUSA00419_00-GTA5000000000000",
        version: "1.0",
        size: 51539607552,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi7qkEUE4EX4FL_ArO5BrmUWRZHOyfW_nBuUJZr4MUvBGPw27swkk6mICitdXzG7EC5NEayg9ag_djWHOzOh4mcDx4jQVDimKxxhal9kwvrm0tEdqCEmgf9D2YCwEVnrRoeM6zzkUU7wgVs7JAXJRKjFWTHovL8rR2HvAhRmpscGRYzt94flSkIc-iZE1qv/w400-h224/g1.jpg",
        description: "Grand Theft Auto V adalah salah satu game aksi-petualangan terpopuler yang dirilis oleh Rockstar Games.Grand Theft Auto V adalah game aksi-petualangan yang menawarkan pengalaman dunia terbuka yang mendalam dan luas. Dalam game ini, Anda akan menjelajahi kota Los Santos yang kaya dengan berbagai aktivitas dan misi, serta mengikuti kisah tiga karakter yang saling terhubung dalam dunia kriminal.\n\nIkuti kisah tiga protagonis utama — Michael De Santa, Franklin Clinton, dan Trevor Philips — yang masing-masing memiliki latar belakang dan motivasi yang berbeda. Cerita ini terjalin dalam berbagai misi yang menarik dan penuh aksi.",
        url: "https://eeur1.akirabox.com/uploads/users/AY2xm0Ao3RO1/coWqnczUZKGdm9emJde-%5BPS4ID%5D-gtav.v1.00-00411.pkg?access=wahVHZntWayhWYtRGOwcXa5MGc1NWclJmbsdWb",
        rating: "M",
        publisher: "Rockstar Games",
        downloads: 0,
        "createdAt": "2026-02-06T23:47:13.918Z",
        "updatedAt": "2026-02-07T03:30:04.965Z"
    },
    {
        id: 3,
        title: "God of War Ragnarok",
        category: "games",
        contentId: "EP9000-CUSA07368_00-GODOFWAR0000000",
        version: "1.00",
        size: 90623809946,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi-ce5Kb_RyDM7i640rvze82ntIGugPHxtaxsxuZ0gh5Ws4NVd-DBmvzaUptEkD7UGQUXS1TqyLfXMTkZQppytk317NzjXmAOglkXKVeIX06qn9PkGYcjRYBo_4Hq6mCGfW3D6gXxkXmHZYRYe93Fsc25OxLR84zmD7_K7D_ptufef73GoiVpsmRxk0SZI-/w400-h221/g1.jpg",
        description: "God of War Ragnarok adalah sekuel dari game “God of War” (2018) yang dikembangkan oleh Santa Monica Studio dan dirilis oleh Sony Interactive Entertainment. Game ini melanjutkan kisah Kratos dan putranya, Atreus, dalam sebuah petualangan epik di dunia mitologi Nordik.\n\nCerita yang Mendalam Lanjutkan perjalanan Kratos dan Atreus saat mereka menghadapi ancaman dari para dewa Nordik dan kekuatan jahat yang ingin menghancurkan dunia.\nGameplay yang Ditingkatkan: Nikmati pertarungan yang intens dengan berbagai kemampuan dan senjata baru. Kombinasi serangan yang mematikan dan strategi tempur yang mendalam.\nDunia Terbuka: Eksplorasi dunia yang lebih luas dan detail, dengan berbagai lokasi yang dapat dijelajahi, termasuk wilayah baru dan musuh yang lebih kuat.\nGrafis dan Visual: Dapatkan pengalaman visual yang memukau dengan grafis yang lebih baik dan desain dunia yang kaya dan detail.",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/corDcjxIdddqM5Sy8de-%5BPS4ID%5D-God.of.War.Ragnarok_CUSA34386_v1.00_%5B9.00%5D_OPOISSO893.pkg?access=QZhhDZutWcy5WY0R2dwQzanFzN4Yjc0I2YsBXb&token=PzEhXy0lM1kjDhZFCwdAIwUTXDkFBgAVFg4ZNCc0PTVXVUFTUj4YRUpRQjQ_WEBEVDwtJDQuJyc3LkpSV08eHwM",
        rating: "M",
        publisher: "Sony Interactive Entertainment",
        downloads: 0,
        "createdAt": "2026-02-06T21:00:33.918Z",
        "updatedAt": "2026-02-07T03:29:48.595Z"
    },
    {
        id: 4,
        title: "Red Dead Redemption",
        category: "games",
        contentId: "EP1004-CUSA03041_00-RDR2S00000000000",
        version: "1.00",
        size: 107374182400,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjmJko6RN2tWqEsrfqA1QzLGTcVUuiV7qEZvvjcLge1zSFG-FuOEO97TL4gMZLsq-SRtnJcQ4UyPtF3C-lJqYEDdFHTKIGBAJHpXMGKClsCtSbxoLZ4QfuKohjTG_kf6uKTnC72bdV1FiE9OVzCm0rOB9ucEmk93dzNYEKR4dp2c1SXn2zNnFyLY4RJCe2V/w400-h225/Red%20Dead%20Redemption.jpg",
        description: "Red Dead Redemption  adalah game aksi-petualangan yang dirilis oleh Rockstar Games.Red Dead Redemption  adalah sebuah game aksi-petualangan yang menawarkan pengalaman dunia terbuka yang mendalam dan realistis, berlatar belakang Amerika Serikat akhir abad ke-19. Game ini merupakan prekuel dari Red Dead Redemption dan menempatkan pemain dalam peran Arthur Morgan, seorang anggota kelompok penjahat yang menghadapi berbagai tantangan dalam dunia yang sedang berubah.",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/coOANZt2HFNeuD9A0de-%5BPS4ID%5D-Red.Dead.Redemption.v1.00-36843.pkg?access=AMhVHZ5tmcyJWY6RGMrFHbwQWZ1RWcqFzZtdTb&token=PzEhXy0lM1k2BBZFIAQPEEozFw8BDB4ADQ4cRRJQQERUTEFdXFVdWhQKFQ",
        rating: "M",
        publisher: "Rockstar Games",
        downloads: 0,
        "createdAt": "2026-02-06T18:13:53.918Z",
        "updatedAt": "2026-02-07T03:36:40.600Z"
    },
    {
        id: 5,
        title: "The Last of Us Part II",
        category: "games",
        contentId: "EP9000-CUSA07820_00-THELASTOFUSPART2",
        version: "1.00",
        size: 92943092285,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEim_D4wWYbM3FnJl5Lhwf9QqMqZXBe7LDJ5_F2nj86w6jXwMjirrH3fF6LLGt3WZ9cDZZoh00wIYNImGjSZjXFKCypTj5FUc_7Vbp9BRs3FPX56BaSqMQsqRtFduJfVR5pKuIeru9OOVgIlrRlTiRjkC3ceui5GahBh91oMSjNYqdAa_EM-wg4le0wDRLP6/w400-h225/The%20Last%20of%20Us%20Part%20II.jpg",
        description: "The Last of Us Part II adalah sekuel yang sangat dinantikan dari game pemenang penghargaan, The Last of Us, yang dikembangkan oleh Naughty Dog untuk PlayStation 4. Dalam game ini, kamu akan melanjutkan perjalanan emosional dan mendalam di dunia pasca-apokaliptik yang penuh dengan ketegangan dan konflik.\n\nIkuti kisah Ellie, yang kini menjadi protagonis utama, saat ia menghadapi tantangan baru dan perjalanan emosional yang berat. Cerita ini menggali tema tentang balas dendam, pengampunan, dan kompleksitas moral, menjadikannya sebuah pengalaman naratif yang mendalam dan penuh emosi.",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/coOZrp2bhnRFcnWsode-%5BPS4ID%5D-The.Last.of.Us.Part.2_CUSA10249_v1.00-PS4.pkg?access=AOhBHZ0t2byJWYkRmYvZDOhZHbs9mcpJGdsVWb&token=PzEhXy0lM1kwCRdFKAAdAEoOFEUxEkAkBRMGRVY-LSE3IENbVlVXKxJQXFtUTD4nUE8CAAM",
        rating: "M",
        publisher: "Sony Interactive Entertainment",
        downloads: 0,
        "createdAt": "2026-02-06T15:27:13.918Z",
        "updatedAt": "2026-02-07T03:39:26.583Z"
    },
    {
        id: 7,
        title: "Ghost of Tsushima",
        category: "games",
        contentId: "EP9000-CUSA17280_00-GHOSTTSUSHIMAMAIN",
        version: "2.24",
        size: 48651242045,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg3h7JJSjS55AoXYnTAnG6BfATMPBa-p5q5yjGi42YRQsUJ2DTguJtlp1wPpIlKN_VTEmAX7uzd9j2453-QDZurglCSlevhfEecrbqKHHs2aze9WAKcnlJnKdCxGyGZIgLZ-Mkz5fbA6vMjb266_qs8d4VfvqmTuZQh9dPxD5MpLD201H3FvCj6944e6Mjg/w400-h229/G1.jpg",
        description: "Ghost of Tsushima Director’s Cut adalah versi perluasan dari permainan aksi petualangan yang sangat dihargai, dirilis untuk PlayStation 4 dan PlayStation 5. Dikembangkan oleh Sucker Punch Productions dan dipublikasikan oleh Sony Interactive Entertainment, permainan ini menempatkan1 Player pemain dalam peran Jin Sakai, seorang samurai yang bertempur untuk melindungi pulau Tsushima dari invasi Mongol pada abad ke-13.",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/coY6liDDlmWHu9Lecde-%5BPS4ID%60%5D-Ghost.of.Tsushima_CUSA13323_FULLGAME_v2.24_%5B9.00-11.00%5D-PS4.pkg?access=QOhhDZws2cyJWYrR2dwI3bsl3c25mc2JWYsJTb&token=PzEhXy0lDilJJhoEFxVAGwJPJhgREgYdCQAtKDEyL0VXUkBYOyc7OCgmMyYhPhhGSlNGND9YQERUTENaSlFeKUkxIV9KEQUT",
        rating: "M",
        publisher: "Sucker Punch Productions",
        downloads: 0,
        "createdAt": "2026-02-06T09:53:53.918Z",
        "updatedAt": "2026-02-07T03:47:47.299Z"
    },
    {
        id: 9,
        title: "Minecraft PS4 Edition",
        category: "games",
        contentId: "EP1004-CUSA00744_00-MINECRAFTPS40001",
        version: "1.00",
        size: 107374182,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh_QYayD0v4CM_30PrN1iUZEZd5iCB9WXbkb5q4NFHvVgnxEUoAi6-c_KYjVnBXfs_Fhz9PeH87s8kWU5hOM6p0BYG-P-ndM_IC0zXtB57_hi7PZ7qDEH2DPU9En0IIeeT2x4Mb-6bgNkBNB_ZQH68ak3lQTqyFJ75LS1TAzf4yM1eNQcypShuLC-cB728x/w400-h215/Minecraft%20PlayStation%204%20Edition.jpg",
        description: "Game sandbox legendaris. Bangun, tambang, dan bertahan hidup di dunia blok!",
        url: "https://eeur1.akirabox.com/uploads/users/AY2xm0Ao3RO1/coNj1B2ssNUoil3Lade-%5BPS4ID%5D-minecraft.v1.00-00265.pkg?access=QOhxGZktGayZTY0QGawI2bytmN4kDd2J2ZsZTb",
        rating: "E10+",
        publisher: "Mojang Studios",
        downloads: 0,
        "createdAt": "2026-02-06T04:20:33.918Z",
        "updatedAt": "2026-02-07T04:46:27.929Z"
    },
    {
        id: 10,
        title: "EA Sports FC 26",
        category: "games",
        contentId: "EP0001-CUSA32278_00-FIFAFC24DELDX000",
        version: "1.0",
        size: 15945066086,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhfaOmGIyJ-s5pLu5OsW0WNb7UfD5AztLpk3QY_rxvjgRyZcIKq4Ah2Z_-WPw0rwbo8gmKfiek5FnI8YGXtwAgiIzImTZ7C5UCdSCq1jwjFDHP4YOtGRuuLy0BS2VmS7pzbcZq97Y2mYjpPKilvLDD7z_7xBilsbs_ccMQXyPFr6W500NtP8Fy6Bbzes1U5/w400-h225/EA%20Sports%20FC%2026.jpg",
        description: "EA Sports FC 26 untuk PS4 menghadirkan pengalaman sepak bola yang lebih tajam berkat sejumlah penyempurnaan gameplay berdasarkan masukan komunitas. Kamu akan merasakan dribel yang lebih responsif, posisi AI pemain yang lebih pintar, dan reaksi kiper yang lebih alami sehingga pertandingan terasa lebih realistis.",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/cooXBSDu64iF4rxt6de-%5BPS4ID%5D-EA.SPORTS.FC.26_CUSA52342_v1.00_%5B12.50%5D_OPOISSO893.pkg?access=AOhxGZ3sWaydTY2R2d4kWe4wWczIXd0JGdshXb&token=PzEhXy0lM1khIFw4NC48IDdPNChKU1grJzQhKlFTXUBWPgRaSlFeKz9QQEVRUTMrKzE9IjcyIUxdUlwbDwY",
        rating: "E",
        publisher: "Electronic Arts",
        downloads: 0,
        "createdAt": "2026-02-06T01:33:53.918Z",
        "updatedAt": "2026-02-07T04:50:26.056Z"
    },
    {
        id: 11,
        title: "Mortal Kombat 11",
        category: "games",
        contentId: "EP1018-CUSA14335_00-MORTALKOMBAT1111",
        version: "1.00",
        size: 39889508762,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjBOBOEuzXiygdDG33DAZ14ll9D1WHVbfUg4c2uLgCmTmuq_kBIWZVYepZMrvR3kkGO0risIOaNwlJCJTPGMTkk_llKGY3b-6WC0PZQ3Q3XqfZYduMu7ozscff5jsdOqkMhPEgw3Z3XJaJS8rXtK2b06vTRjA69UqoEMebeIYWECRlualf7EtU8nbWUO83q/w400-h220/k1.jpg",
        description: "Mortal Kombat 11 Ultimate Edition adalah edisi khusus dari game pertarungan legendaris yang dirilis untuk PlayStation 4.\n\nMortal Kombat 11 Ultimate Edition adalah versi lengkap dan terbaru dari game pertarungan terkenal Mortal Kombat 11. Edisi ini mencakup semua konten tambahan dan ekspansi yang dirilis untuk game ini, menawarkan pengalaman bertarung yang lebih komprehensif dan mendalam.",
        url: "https://eeur1.akirabox.com/uploads/users/AY2xm0Ao3RO1/cozdGfz4p4EApEZesde-%5BPS4ID%5D-Mortal.Kombat.11.Ultimate-CUSA11379-EUR-Game-v1.00_%5B6.72%5D_OPOISSO893.pkg?access=wMhlGZ5tGeyZTYjRWYwEWe2kzbkBXdzIWYshWb",
        rating: "M",
        publisher: "Warner Bros",
        downloads: 0,
        "createdAt": "2026-02-05T22:47:13.918Z",
        "updatedAt": "2026-02-07T04:56:36.009Z"
    },
    {
        id: 12,
        title: "Resident Evil 2 Remake",
        category: "games",
        contentId: "EP0102-CUSA14183_00-BH2REMASTER00000",
        version: "1.00",
        size: 23203560817,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgqUOp8J8cPRRd_77Cx_mXocMDdjhYb1MlpvMxvpUjns5-rVc7PN3RPY1YFvYs_jimvT-bP_GRIM54B9RoFJwe8fLF2c0qgXqjqvYAq9U7qxVP_6lvVaJZcrRAc-eppsrOUX5nobKA_LNAEdqG2BMIuMmYU8o2BPOHt4I3qSx7_DhoyLRTdXhKYj4d5MsI8/w400-h225/Resident%20Evil%202%20Remake%20Deluxe%20Edition.png",
        description: "Resident Evil 2 Remake Deluxe Edition membawa kembali pengalaman menegangkan dari game survival horror ikonik dengan grafis modern dan mekanisme gameplay yang diperbarui. Versi Deluxe Edition menawarkan lebih dari sekadar remaster; ini adalah pembaharuan yang menyegarkan dengan tambahan konten eksklusif yang memperkaya pengalaman bermain.",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/coN80EtQfUQQKzsuYde-%5BPS4ID%5D-Resident.Evil.2.v1.00-CUSA09171.pkg?access=gahZHZ0tWOyJTY3QmZjl2N0V3dxEmdyJGOsNWb&token=PzEhXy0lM1k2BAECAAQAAEokBAIIT1xaElBcW1RMLSE3IEJSVVZfWhQKFQ",
        rating: "M",
        publisher: "Capcom",
        downloads: 0,
        "createdAt": "2026-02-05T20:00:33.918Z",
        "updatedAt": "2026-02-07T05:15:44.966Z"
    },
    {
        id: 13,
        title: "Cyberpunk 2077",
        category: "games",
        contentId: "EP4497-CUSA16512_00-CYBERPUNK2077000",
        version: "2.1",
        size: 70877697802,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhtaec_nvWuhsCBFZvycYReqdX-Lvs440W55iXZJU7asv4wbVycCGcWMeRdIhgPksjNondjBTFgpIWdDGGFyAFfPE-7U2OKsxOAu6U7icwB4cUf-2cVLggsZkUYeBw_N1DafHXOBslN9oJJJ59j6aG8i9OBTX3FJhBnprnnkAhSUCX29M7OPb6Ph5ZHIVZ3/w400-h225/Cyberpunk%202077.jpg",
        description: "RPG open-world di masa depan dystopia. Jadilah cyberpunk legendaris!",
        url: "https://eeur1.akirabox.com/uploads/users/AY2xm0Ao3RO1/co6jDfaGfGnq67bWede-%5BPS4ID%5D.cyb2k77.v1.61.merged-16579.pkg?access=gNhBDZptGOylTY0QWMjtGanRHN3YmdyJWbsdTb",
        rating: "M",
        publisher: "CD Projekt Red",
        downloads: 0,
        "createdAt": "2026-02-05T17:13:53.918Z",
        "updatedAt": "2026-02-07T05:20:37.518Z"
    },
    {
        id: 14,
        title: "PES SGR Patch Winter 2026",
        category: "games",
        contentId: "EP0002-CUSA08283_00-MWII202300000000",
        version: "26.2",
        size: 30494267802,
        image: "https://down-id.img.susercontent.com/file/id-11134207-8224z-ml0d2d5ckzd06e",
        description: "SGR Patch PES 2018 Winter Season 2026 (untuk PS4 HEN) adalah modifikasi yang memperbarui PES 2018 base dengan konten musim dingin 2026. Fitur utamanya mencakup transfer pemain terbaru, pembaruan skuad, jersey tim terkini, serta kompetisi segar untuk menghadirkan pengalaman modern.",
        url: "https://eeur1.akirabox.com/uploads/users/AY2xm0Ao3RO1/co8njAV3CGeA290fVde-PES 2018 CUSA08283 SGR Patch Winter 2026 BaseGame.pkg?access=gdhZHZwsGeyZTY0QWe0MHaoNzal1mcnFDZtlXb",
        rating: "M",
        publisher: "Konami",
        downloads: 19870,
        "createdAt": "2026-02-05T14:27:13.918Z"
    },
    {
        id: 201,
        title: "PES 2026 - REV 2 Update",
        category: "updates",
        contentId: "EP9000-CUSA00207_00-PES2026UPDATE002",
        version: "2.0",
        size: 4448720998,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSnWPUdC9FSVy6WsmHaRTi1GFfPD9dtPg6rQ&s",
        description: "Patch dan update terbaru untuk PES 2026. Fix bug dan peningkatan performa.",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/co9JVM7BGy6lBA3ROde-REV2%20PES%2026%20BITBOX%20PATCH.pkg?access=QehVDZ3tGNyFXYjRGezFTMyJmMqZmbvVDcsFTb&token=NiQkWUQxKydEU0RLJig6Nis5UjslNS08ShEZDA",
        rating: "E",
        publisher: "Konami",
        downloads: 0,
        "createdAt": "2026-02-03T20:47:13.918Z",
        "updatedAt": "2026-02-07T03:31:40.617Z"
    },
    {
        id: 201,
        title: "PES SGR Patch Winter 2026 - REV 0",
        category: "updates",
        contentId: "EP0002-CUSA08283_00",
        version: "2.0",
        size: 8804682956.8,
        image: "https://down-id.img.susercontent.com/file/id-11134207-8224z-ml0d2d5ckzd06e",
        description: "Patch dan update terbaru untuk PES 2026. Fix bug dan peningkatan performa.",
        url: "https://eeur1.akirabox.com/uploads/users/AY2xm0Ao3RO1/coHjBe4d2Ds7AevFide-PES 2018 CUSA08283 SGR Patch Winter 2026 UpdateGame Rev.0.pkg?access=gahZGZ5t2Yy9WYoRGMwk3dxcTZqNjciFDatZXb",
        rating: "E",
        publisher: "Konami",
        downloads: 0,
    },
    {
        id: 202,
        title: "God of War - Update",
        category: "updates",
        contentId: "EP9000-CUSA07368_00-B00000000000000",
        version: "6.05",
        size: 25308094792,
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi-ce5Kb_RyDM7i640rvze82ntIGugPHxtaxsxuZ0gh5Ws4NVd-DBmvzaUptEkD7UGQUXS1TqyLfXMTkZQppytk317NzjXmAOglkXKVeIX06qn9PkGYcjRYBo_4Hq6mCGfW3D6gXxkXmHZYRYe93Fsc25OxLR84zmD7_K7D_ptufef73GoiVpsmRxk0SZI-/w400-h221/g1.jpg",
        description: "Update 6.05 menambahkan New Game+ dan Photo Mode!",
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/coc6JogHtLCS8k5TOde-%5BPS4ID%5D-God.of.War.Ragnarok_CUSA34386_v6.05_%5B9.00%5D-PS4.pkg?access=gahZDZntGeyFXYhRWZjZ2MwF2ZllncoJ2ZsVWb&token=PzEhXy0lM1kjDhZFCwdAIwUTXDkFBgAVFg4ZNCc0PTVXVUFTUj4YQkpRRzQ_WEBEVDxfOzdVQAQPBg",
        rating: "M",
        publisher: "Sony Interactive Entertainment",
        downloads: 0,
        "createdAt": "2026-02-03T18:00:33.918Z",
        "updatedAt": "2026-02-07T03:34:07.448Z"
    },
    {
        id: 307,
        "createdAt": "2026-02-07T04:02:04.486Z",
        downloads: 0,
        title: "The Last of Us Part II - Update",
        category: "updates",
        publisher: "Sony Interactive Entertainment",
        version: "1.09",
        rating: "E",
        size: 48962627174,
        url: "https://download.akirabox.com/uploads/users/AY2xm0Ao3RO1/codg2Z2AHeBbC21jbde-hako.tloupii.v1.09.Update-10249.rar?access=QZhlGZ3tGNyRTYtRWcwcjMpVTeyJjcyJGesBXb&token=DAAZBEoVAhsRERsCShdfWlRYXD4UBQ8AAUxDW1ZVV1oWAAA",
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEim_D4wWYbM3FnJl5Lhwf9QqMqZXBe7LDJ5_F2nj86w6jXwMjirrH3fF6LLGt3WZ9cDZZoh00wIYNImGjSZjXFKCypTj5FUc_7Vbp9BRs3FPX56BaSqMQsqRtFduJfVR5pKuIeru9OOVgIlrRlTiRjkC3ceui5GahBh91oMSjNYqdAa_EM-wg4le0wDRLP6/w400-h225/The%20Last%20of%20Us%20Part%20II.jpg",
        description: ""
    },
    {
        id: 308,
        "createdAt": "2026-02-07T01:15:24.486Z",
        downloads: 0,
        title: "GTA V - Grand Theft Auto V",
        category: "updates",
        publisher: "Rockstar Games",
        version: "1.52",
        rating: "E",
        size: 48500918190,
        url: "https://eeur1.akirabox.com/uploads/users/AY2xm0Ao3RO1/cogObqdAKGZIoIXt8de-%5BPS4ID%5D-Grand.Theft.Auto.V.Update.v1.52-CUSA00411.pkg?access=AZhtGZ0t2NyVXYxRWZ3J3Y2VmcxkncyJWMshTb",
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi7qkEUE4EX4FL_ArO5BrmUWRZHOyfW_nBuUJZr4MUvBGPw27swkk6mICitdXzG7EC5NEayg9ag_djWHOzOh4mcDx4jQVDimKxxhal9kwvrm0tEdqCEmgf9D2YCwEVnrRoeM6zzkUU7wgVs7JAXJRKjFWTHovL8rR2HvAhRmpscGRYzt94flSkIc-iZE1qv/w400-h224/g1.jpg",
        description: "Grand Theft Auto V adalah salah satu game aksi-petualangan terpopuler yang dirilis oleh Rockstar Games.Grand Theft Auto V adalah game aksi-petualangan yang menawarkan pengalaman dunia terbuka yang mendalam dan luas. Dalam game ini, Anda akan menjelajahi kota Los Santos yang kaya dengan berbagai aktivitas dan misi, serta mengikuti kisah tiga karakter yang saling terhubung dalam dunia kriminal.\n\nIkuti kisah tiga protagonis utama — Michael De Santa, Franklin Clinton, dan Trevor Philips — yang masing-masing memiliki latar belakang dan motivasi yang berbeda. Cerita ini terjalin dalam berbagai misi yang menarik dan penuh aksi."
    }
];

// ========== HELPER FUNCTIONS ==========

function getAllGames() {
    return PS4_GAME_CATALOG;
}

function getGamesByCategory(category) {
    if (category === 'all') return PS4_GAME_CATALOG;
    return PS4_GAME_CATALOG.filter(game => game.category === category);
}

function getGameById(id) {
    return PS4_GAME_CATALOG.find(game => game.id === id);
}

function searchGames(query) {
    const lowerQuery = query.toLowerCase();
    return PS4_GAME_CATALOG.filter(game => 
        game.title.toLowerCase().includes(lowerQuery) ||
        (game.description && game.description.toLowerCase().includes(lowerQuery))
    );
}

function getFeaturedGames(limit = 4) {
    return PS4_GAME_CATALOG
        .filter(game => game.url && !game.url.includes('example.com'))
        .slice(0, limit);
}

function getTopDownloads(limit = 5) {
    return [...PS4_GAME_CATALOG]
        .sort((a, b) => (b.downloads || 0) - (a.downloads || 0))
        .slice(0, limit);
}

function getGameStats() {
    const games = PS4_GAME_CATALOG.filter(g => g.category === 'games');
    const apps = PS4_GAME_CATALOG.filter(g => g.category === 'apps');
    const updates = PS4_GAME_CATALOG.filter(g => g.category === 'updates');
    const dlc = PS4_GAME_CATALOG.filter(g => g.category === 'dlc');
    
    const totalSize = PS4_GAME_CATALOG.reduce((acc, g) => acc + (g.size || 0), 0);
    
    return {
        totalGames: games.length,
        totalApps: apps.length,
        totalUpdates: updates.length,
        totalDLC: dlc.length,
        totalItems: PS4_GAME_CATALOG.length,
        totalSize: totalSize
    };
}

function formatSize(bytes) {
    if (bytes === 0) return '0 B';
    const k = 1024;
    const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
}
